version: '3.8'
services:
  client:
    build: './docker'
    ports:
      - "8080:8080"
    container_name: client
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
