version: '3.8'
services:
  jotting_client:
    build: './docker'
    ports:
      - "8080:8080"
    container_name: jotting_client
    volumes:
      - ./:/app
      - node_modules_volume:/app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules_volume: