name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 14.17.4
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.4
      - name: yarn install
        run: yarn install
      - name: Run jest tests
        run: yarn test:unit
      - name: Notify on Slack
        id: notify-slack-success
        if: success()
        run: |
          DATE=`TZ=-9 date "+%s"`
          echo "{\"attachments\": [{\"color\": \"good\",\"title\": \"[Frontend] テスト！ヨシ！ \", \"title_link\": \"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}\", \"footer\": \"${GITHUB_REF##*/}\", \"ts\": \"$DATE\"}]}" | curl -X POST -H 'Content-type: application/json' -d @- https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK
      - name: Notify on Slack
        id: notify-slack-success
        if: success()
        run: |
          DATE=`TZ=-9 date "+%s"`
          echo "{\"attachments\": [{\"color\": \"good\",\"title\": \"[Frontend] テスト！ヨシ！ \", \"title_link\": \"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}\", \"footer\": \"${GITHUB_REF##*/}\", \"ts\": \"$DATE\"}]}" | curl -X POST -H 'Content-type: application/json' -d @- https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK
