name: Reviewdog CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  eslint:
    name: check_eslint_error
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.4]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: Run eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-check
          eslint_flags: "./**/*.{vue,ts,js}"

      - name: "Comment PR with eslint errors"
        uses: actions/github-script@0.3.0
        # if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
            github.issues.createComment({ issue_number, owner, repo, body: 'Hello world ! 👋' });
        # if: failure()
