name: Reviewdog CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  eslint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install
        run: |
          yarn install --frozen-lockfile
        env:
          CI: true
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          eslint_flags: "src/"

      # - name: run eslint strict
      #   run: |
      #     reviewdog -runners=eslint -diff="git diff main" -reporter=github-pr-check -filter-mode=file
      #   env:
      #     REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
